// <?php
// $title = 'Accept Reservation';
// $this->headTitle($title);
// ?>
// <h1><?php echo $this->escapeHtml($title); ?></h1>

// <?php
// $form = $this->form;
// $form->setAttribute('action', $this->url(
//     'food',
//     array(
//         'action' => 'accept',
//         'id'     => $this->id,
//     )
// ));
// $form->prepare();

// echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('title'));
// echo $this->formRow($form->get('location'));
// echo $this->formRow($form->get('creator'));
// echo $this->formSubmit($form->get('submit'));
// echo $this->form()->closeTag();
