<?php
$title = 'Edit Reservation';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'food',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('location'));
echo $this->formRow($form->get('creator'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<form action="update_res.asp">
  Date<input type="text" name="date"><br>
  Time<input type="text" name="time"><br>
  Rating<input type="text" name="rating"><br>
  Attending<input type="text" name="attending"><br>
  <input type="submit" value="Submit">
</form>