<?php
$title = 'Edit Reservation';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'food',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

$res_id = $this->id;

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('location'));
echo $this->formRow($form->get('creator'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

Date<input id="input_date" type="text" name="date"><br>
Time<input id="input_time" type="text" name="time"><br>
Rating<input id="input_rating" type="text" name="rating"><br>
Attending<input id="input_attending" type="text" name="attending"><br>
<button onclick="editReservation()">Submit</button>

<?php 
readPreviousResInfo($res_id);
function readPreviousResInfo($res_id){
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL,"http://outtoeat.arlenburroughs.com/read_details.php?filename=".$res_id);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS,"");

	// receive server response ...
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

	$server_output = curl_exec ($ch);
	$date = strtok($server_output, "\n");
	$time =  strtok("\n");
	$rating = strtok("\n");
	$attending = strtok("\n");
	echo "<script> document.getElementById('input_date').value = \"".$date."\"
	document.getElementById('input_time').value= \"".$time."\"
	document.getElementById('input_rating').value= \"".$rating."\"
	document.getElementById('input_attending').value= \"".$attending."\" </script>";
	curl_close ($ch);
}
?>

<script>
function editReservation() {
    var date = document.getElementById('input_date').value
	var time = document.getElementById('input_time').value
	var rating = document.getElementById('input_rating').value
	var attending = document.getElementById('input_attending').value
	var id = "<?php echo $res_id;?>"
	window.alert("Writing date: "+date+", time: "+time+", rating: "+
		rating+", attending: "+attending+", w/ id: "+id);
	
	var xmlhttp;
	if (window.XMLHttpRequest)
	  {// code for IE7+, Firefox, Chrome, Opera, Safari
		xmlhttp=new XMLHttpRequest();
	  }
	else
	  {// code for IE6, IE5
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	  }
	xmlhttp.onreadystatechange=function()
	  {
	  if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
		document.getElementById("myDiv").innerHTML=xmlhttp.responseText;
		}
	}
	xmlhttp.open("GET","http://outtoeat.arlenburroughs.com/write_details.php?filename="+id+
		"&date="+date+
		"&time="+time+
		"&rating="+rating+
		"&attending="+attending,true);
	xmlhttp.send();
}
</script>