<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
        <script src="//www.parsecdn.com/js/parse-1.3.2.min.js"></script>
        <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('food') ?>">Restaurant Finder</a>
                    <div class="nav-collapse collapse">

                        <!--If User Logged in-->
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('food') ?>"><?php echo $this->translate('My Reservations') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('food', array('action'=>'add'));?>"><?php echo $this->translate('New Reservation') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('food', array('action'=>'random'));?>"><?php echo $this->translate('Random Restaurant')?></a></li>
                            <li class="active"><a href="<?php echo $this->url('user', array('action'=>'edit'));?>"><?php echo $this->translate('Preferences')?></a></li>
                            <li class="active"><a href="<?php echo $this->url('food', array('action'=>'Logout'));?>"><?php echo $this->translate('Logout') ?></a></li>
                        </ul>
                        <!--End If User Logged in-->
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
